
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    restart: unless-stopped

  gradio:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - API_URL=http://api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    command: python -m hometask.gradio_interface
    depends_on:
      - api
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"